### ISSUE TITLE
Cannot translate

### ISSUE THREAD

**Issue by Chris-Hal** [NastuzziSamy/ulauncher-translate#3]
Hi Samy, 
I stuck using your plugin. As in the screenshot, I input the term, but it stuck at Loading as in the screenshot and doesn't display any result. I found  an former issue report, that has taken an unbeautiful direction, that a python translate library needs to be installed. 
I installed translate by `sudo pip install translate`Is this what you mean?

My enviroment is Ulauncher 5.10 on  Linux Mint 19.3.

The Debug output of your extension is as follows_
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/api/client/Client.py", line 54, in on_message
    self.extension.trigger_event(event)
  File "/usr/lib/python3/dist-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
    action = listener.on_event(event, self)
  File "/home/christian/.local/share/ulauncher/extensions/com.github.nastuzzisamy.ulauncher-translate/main.py", line 34, in on_event
    translations = parser.execute()
  File "/home/christian/.local/share/ulauncher/extensions/com.github.nastuzzisamy.ulauncher-translate/src/translate_shell.py", line 81, in execute
    result = subprocess.check_output(self.get_arguments(), encoding='utf-8')
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: 'trans': 'trans'
```

Does it make clear for you what the problem is and how I can solve it?

Thanks and best regards
Christian

![Bildschirmfoto vom 2021-03-16 21-26-09](https://user-images.githubusercontent.com/80788677/111376646-02839800-86a0-11eb-91b3-825a4a2269f6.png)

**Comment by Chris-Hal** [comment]
If somebody else stuck at this point, when the plugin is not working, you need to install translate-shell Link->https://github.com/soimort/translate-shell

```
$ git clone https://github.com/soimort/translate-shell
$ cd translate-shell/
$ make
$ [sudo] make install
```
Afterwards the plugin is working.

**Comment by NastuzziSamy** [comment]
Hi @Chris-Hal thx for your issue and your resolution.

I fixed the extension so now, if you dont have the dep, it will show you how to install it.
